### ISSUE TITLE
Can't --install

### ISSUE THREAD

**Issue by vadosnaprimer** [prekageo/navigation-log#1]
Hi. Getting this error with python 2.7, Win7 x64. Should I try another setup?

```
>python navigation_log.py --install
  File "navigation_log.py", line 32
    f.write(f'"{sys.executable}" "{SCRIPT}"\n')
                                             ^
SyntaxError: invalid syntax
```

**Comment by prekageo** [comment]
I've removed f-strings. Please try again. The script is written for Python 3. If it still doesn't work, consider upgrading to Python 3. If you can't upgrade, I can try to make the script compatible with Python 2.7.

**Comment by vadosnaprimer** [comment]
I got a similar arror

```
  File "navigation_log.py", line 56
    print('Unsupported platform %s.' % system, file=sys.stderr)
                                                   ^
SyntaxError: invalid syntax
```

Installing python 3+ helped (you might wanna mention this as a requirement in the description).

But how do I actually use this tool? Where do I browse the log? Is it limited to just opening the file it's created and reading it?

**Comment by prekageo** [comment]
At the moment, there is no UI for the tool. You have to use `sqlite3` to open the log database and query it with SQL or do a `.dump`.
